In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'name': ['Ram', 'Shyam', 'Hari', 'Krishna'],
    'age': [21, 65, 34, 88]
})

df2 = pd.DataFrame({
    "id" : [1, 2, 3, 5], 
    "principle": [500, 658, 4032, 500], 
    "interest" : [6.3, 4.25, 9.8, 5.6]
})

In [3]:
print(df1, df2)

   id     name  age
0   1      Ram   21
1   2    Shyam   65
2   3     Hari   34
3   4  Krishna   88    id  principle  interest
0   1        500      6.30
1   2        658      4.25
2   3       4032      9.80
3   5        500      5.60

## Concatenation

Concatenation is the process of combining two or more dataframes by appending them along a particular axis. To concatenate two or more dataframes along rows or columns, you can use the `pd.concat()` function from the `pandas` library.

In [4]:
# Basic
pd.concat(
    [df1,df2]
)

   id     name   age  principle  interest
0   1      Ram  21.0        NaN       NaN
1   2    Shyam  65.0        NaN       NaN
2   3     Hari  34.0        NaN       NaN
3   4  Krishna  88.0        NaN       NaN
0   1      NaN   NaN      500.0      6.30
1   2      NaN   NaN      658.0      4.25
2   3      NaN   NaN     4032.0      9.80
3   5      NaN   NaN      500.0      5.60

In [5]:
# ignore_index = True
pd.concat(
    [df1, df2],
    ignore_index= True
)

   id     name   age  principle  interest
0   1      Ram  21.0        NaN       NaN
1   2    Shyam  65.0        NaN       NaN
2   3     Hari  34.0        NaN       NaN
3   4  Krishna  88.0        NaN       NaN
4   1      NaN   NaN      500.0      6.30
5   2      NaN   NaN      658.0      4.25
6   3      NaN   NaN     4032.0      9.80
7   5      NaN   NaN      500.0      5.60

In [6]:
# Horizontal Concatenation
pd.concat(
    [df1, df2],
    axis= 1
)

   id     name  age  id  principle  interest
0   1      Ram   21   1        500      6.30
1   2    Shyam   65   2        658      4.25
2   3     Hari   34   3       4032      9.80
3   4  Krishna   88   5        500      5.60

In [7]:
# Different Number of Rows
data1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Marks": [85, 62, 91]
})

data2 = pd.DataFrame({
    "City": ["Kathmandu", "Pokhara"]
})

pd.concat(
    [data1, data2],
    axis= 1
)

      Name  Marks       City
0    Alice     85  Kathmandu
1      Bob     62    Pokhara
2  Charlie     91        NaN

In [8]:
# Different Columns
data1 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Marks": [85, 62]
})

data2 = pd.DataFrame({
    "Name": ["Charlie", "David"],
    "Age": [19, 22]
})

pd.concat(
    [data1, data2],
    axis= 0,
    ignore_index= True
)

      Name  Marks   Age
0    Alice   85.0   NaN
1      Bob   62.0   NaN
2  Charlie    NaN  19.0
3    David    NaN  22.0

In [9]:
# join

data1 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Marks": [85, 62]
})

data2 = pd.DataFrame({
    "Name": ["Charlie", "David"],
    "Age": [19, 22]
})

pd.concat(
    [data1, data2],
    axis= 0,
    join= "inner",
    ignore_index= True
)

      Name
0    Alice
1      Bob
2  Charlie
3    David

In [10]:
# join="outer" vs join="inner"

data1 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Marks": [85, 62],
    "City": ["Kathmandu", "Pokhara"]
})

data2 = pd.DataFrame({
    "Name": ["Charlie", "David"],
    "Age": [19, 22],
    "City": ["Lalitpur", "Bhaktapur"]
})

print(pd.concat(
    [data1, data2],
    join= "outer",
    ignore_index= True
))

print("-" * 50)

print(pd.concat(
    [data1, data2],
    join= "inner",
    ignore_index= True
))

      Name  Marks       City   Age
0    Alice   85.0  Kathmandu   NaN
1      Bob   62.0    Pokhara   NaN
2  Charlie    NaN   Lalitpur  19.0
3    David    NaN  Bhaktapur  22.0
--------------------------------------------------
      Name       City
0    Alice  Kathmandu
1      Bob    Pokhara
2  Charlie   Lalitpur
3    David  Bhaktapur