# Handling Incorrect Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.DataFrame({
    'id': [1, 3, 5, 7, 9],
    'name': ['John', 'Jane', 'Jennifer', 'Johan', 'Jeff'],
    'age': [25, -32, 19, 42, '55'],
    'gender': ["M", "M", "Z", "F", "F"],
    'income': [400, 700, 300, np.nan, 600]
})

data

   id      name  age gender  income
0   1      John   25      M   400.0
1   3      Jane  -32      M   700.0
2   5  Jennifer   19      Z   300.0
3   7     Johan   42      F     NaN
4   9      Jeff   55      F   600.0

In [3]:
data.info()
data.describe(include='all')

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   name    5 non-null      str
 2   age     5 non-null      object
 3   gender  5 non-null      str
 4   income  4 non-null      float64
dtypes: float64(1), int64(1), object(1), str(2)
memory usage: 332.0+ bytes

              id  name   age gender      income
count   5.000000     5   5.0      5    4.000000
unique       NaN     5   5.0      3         NaN
top          NaN  John  25.0      M         NaN
freq         NaN     1   1.0      2         NaN
mean    5.000000   NaN   NaN    NaN  500.000000
std     3.162278   NaN   NaN    NaN  182.574186
min     1.000000   NaN   NaN    NaN  300.000000
25%     3.000000   NaN   NaN    NaN  375.000000
50%     5.000000   NaN   NaN    NaN  500.000000
75%     7.000000   NaN   NaN    NaN  625.000000
max     9.000000   NaN   NaN    NaN  700.000000

In [4]:
data.isna().sum()

id        0
name      0
age       0
gender    0
income    1
dtype: int64

In [5]:
data.dtypes

id          int64
name          str
age        object
gender        str
income    float64
dtype: object

In [6]:
# Negative Age
data = data.astype({
    'age': 'int32'
})

data.age = abs(data.age)
data

   id      name  age gender  income
0   1      John   25      M   400.0
1   3      Jane   32      M   700.0
2   5  Jennifer   19      Z   300.0
3   7     Johan   42      F     NaN
4   9      Jeff   55      F   600.0

In [7]:
# Incorrect Gender
data = data[data.gender.isin(["M", "F"])]

In [8]:
# Fill na values
mean = round(data.income.mean(), 1)
data.income = data.income.fillna(mean)

In [9]:
data

   id   name  age gender  income
0   1   John   25      M   400.0
1   3   Jane   32      M   700.0
3   7  Johan   42      F   566.7
4   9   Jeff   55      F   600.0