In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.5'

## Datatype of Pandas
1. DataFrame: 2D Table with rows and columns
2. Series: 1D array-like , can hold any data type such as integers, strings, floating-point numbers, and Python objescts

## Creating DataFrame

In [3]:
data = {
    "name": ["Bob", "Aman", "Charls", "Jhon"],
    "age": [25, 56, 15, 78]
}

In [4]:
df = pd.DataFrame(data)
df

     name  age
0     Bob   25
1    Aman   56
2  Charls   15
3    Jhon   78

In [5]:
my_data = {
    "id": 1,
    "name": "Pradeep",
    "age": 25
}

res = pd.DataFrame(data=my_data, index=["a", "b", "c"], columns=["id", "name", "age"])
res

   id     name  age
a   1  Pradeep   25
b   1  Pradeep   25
c   1  Pradeep   25

## Creating Series

In [6]:
a = ["g", "h", "i", "j"]
res = pd.Series(a)
res

0    g
1    h
2    i
3    j
dtype: str

In [7]:
a = ["1", "2", "3", "4"]
res = pd.Series(data= a, index= ["a", "b", "c", "d"], dtype= "int8", name= "list of number", copy= False)
res

a    1
b    2
c    3
d    4
Name: list of number, dtype: int8

In [8]:

my_data = {
    "id": 1,
    "name": "pradeep",
    "age": 25,
}
res_dict = pd.Series(data=my_data)
res_dict

id            1
name    pradeep
age          25
dtype: object

## Reading Data From Files

* `pd.read_csv(file_path, delimiter=",")`: Reads CSV (Comma Separated Value) file and returns a Pandas DataFrame 
* file_path: Path to csv file
* delimiter: Symbol separating columns (default= ",")

In [9]:
titanic_df = pd.read_csv("../data/titanic_data.csv", delimiter=",", header=0)
titanic_df.shape

(891, 12)

In [10]:
type(titanic_df)

pandas.DataFrame

## Accessing Data

In [11]:
# Sneak Peek
titanic_df.head() # it will give the data from start

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
titanic_df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [13]:
titanic_df.tail() # it will give the data from end

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

## Basic Properties

In [14]:
titanic_df.shape

(891, 12)

In [15]:
titanic_df.ndim

2

In [16]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [17]:
titanic_df.index

RangeIndex(start=0, stop=891, step=1)

In [18]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [19]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [20]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [21]:
# Reading a column
name = titanic_df["Name"]
#or
# name = titanic_df.Name #<- Limited
name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [22]:
type(name)

pandas.Series

In [23]:
name_age = titanic_df[["Name", "Age"]]
name_age

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [24]:
# Reading Rows
second_row = titanic_df.loc[2]
second_row

PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                              26.0
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object